### ISSUE TITLE
Recommend using the latest version of Solidity supported by Truffle.js

### ISSUE THREAD

**Issue by IsaacPayne** [BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts#1]
The latest version of Solidity supported by Truffle.js is 0.4.13, the contracts are all using 0.4.11

**Comment by yaronvel** [comment]
We do use truffle with 0.4.13, We will update pragmas to indicate it.
By the way, latest truffle is now using 0.4.15 solc. But we are tending not to upgrade it.
Latest version (mainly of truffle) is not necessarily to most reliable IMO.

Still, we will use 0.4.13.

**Comment by yaronvel** [comment]
Changed to 0.4.13, beside in open zepplin code.
For the record, this pragma is meaningless to the compiler if its version is > pragma version. 
It is just one of solidity quirks.
Still, we changed it to 0.4.13.

**Comment by OperationNine** [comment]
- [x] Fixed [8962e6a2](https://github.com/KyberNetwork/TokenDistributionContracts/commit/8962e6a2f09cd2a6e30827a2a506b6d773a1f3f5)
