### ISSUE TITLE
Unnecessary return

### ISSUE THREAD

**Issue by IsaacPayne** [BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts#10]
No need to return the result from `burn` as both functions are void

https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/KyberNetworkCrystal.sol#L67

**Comment by yaronvel** [comment]
IMO the return is fine. It is ok to return also in void function.
However, it does raise the question of whether we should have a boolean return value. I guess we should, to be consistent with `transfer`.

**Comment by yaronvel** [comment]
Changed `burn` and `burnFrom` to return a boolean value.

**Comment by OperationNine** [comment]
- [x] Fixed [bdcfe802](https://github.com/KyberNetwork/TokenDistributionContracts/commit/bdcfe80205584f884f56c9ff0aeaeef9d1188c2a)
