### ISSUE TITLE
Should return result of transfer

### ISSUE THREAD

**Issue by IsaacPayne** [BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts#11]
`emergencyERC20Drain` should return the result of transfer so the caller knows if it was successful

https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/KyberNetworkCrystal.sol#L70

**Comment by yaronvel** [comment]
Thanks, will do. (to be precise, I will return true if transfer didn't fail, and throw otherwise).

**Comment by OperationNine** [comment]
- [x] Fixed [bdcfe802](https://github.com/KyberNetwork/TokenDistributionContracts/commit/bdcfe80205584f884f56c9ff0aeaeef9d1188c2a)
