### ISSUE TITLE
Soften Emergency function names

### ISSUE THREAD

**Issue by IsaacPayne** [BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts#12]
Having `emergency` in a function name comes off as alarming, would be better to name something like `collectTokens` like in the [Status contract](https://github.com/status-im/status-network-token/blob/f195a73743f836d3c50b709f29f500a02bac6154/contracts/SNTPlaceHolder.sol#L116)

**Comment by IsaacPayne** [comment]
Same can be said for `function debugBuy()`

**Comment by yaronvel** [comment]
`debugBuy` must be a public function.
The purpose of `debugBuy` is to do manually verification for multisig wallet address.
After deployment, we plan to call it, and see that multisig balance increases by 123 wei.
