### ISSUE TITLE
ProxyBuy?

### ISSUE THREAD

**Issue by IsaacPayne** [BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts#13]
Not clear what proxy does? Could use documentation and/or comments

https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/KyberNetworkTokenSale.sol#L52

**Comment by yaronvel** [comment]
some wallet providers will promote our ICO, and will get fees for that from us.
Each provider (currently, there is only one) is assigned with a 32 bytes hash (for simplicity say hash = 0x1).
The wallet users will call buyProxy with hash = 0x1.
At the end of the ICO we will give x% to the wallet provider from the amount it helped us raised.

So the proxy is a wallet provider. Its user will just click a button and the wallet will compile a tx to buyProxy with the relevant hash for them.


If a so called malicious user wants to help the wallet and use this function with hash = 0x1, then we are fine with that.

**Comment by Janther** [comment]
copy-paste the previous comment to the code?¿?¿?¿
