### ISSUE TITLE
Buy returns uint, ProxyBuy doesn't

### ISSUE THREAD

**Issue by IsaacPayne** [BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts#14]
For consistency we would recommend returning the `amount` from `ProxyBuy` as it behaves almost identically to `Buy`

https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/KyberNetworkTokenSale.sol#L52

**Comment by yaronvel** [comment]
will do. thanks.

**Comment by OperationNine** [comment]
- [x] Fixed [b06da990](https://github.com/KyberNetwork/TokenDistributionContracts/commit/b06da99026b8d30458db9d79f9992f3a6bee9d09)
