### ISSUE TITLE
Comment recommended for slackUsersCap // In ETH

### ISSUE THREAD

**Issue by OperationNine** [BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts#15]
Might be a good idea to put into a comment that the cap is denominated in ETH and not in KNC so there is no confusion

https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/KyberContributorWhitelist.sol#L6

**Comment by yaronvel** [comment]
Added a comment that cap is in wei.

**Comment by OperationNine** [comment]
- [x] Fixed [9b6769ac](https://github.com/KyberNetwork/TokenDistributionContracts/commit/9b6769ac4087c36f28470b4f9507cc3dea4c8995)
