### ISSUE TITLE
slackUsersCap = 7 (needs 18 decimals) 

### ISSUE THREAD

**Issue by OperationNine** [BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts#16]
Cap per contributor is currently set to `7 WEI` instead of `7 ETH` -- Consider changing to `7000000000000000000`

https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/KyberContributorWhitelist.sol#L6

**Comment by yaronvel** [comment]
This is not a bug but a feature :)
Seriously though, given the large amount of registration we expect (up to 50k), we plan to upload addresses before total number of users in list is known.

Hence, the actual cap is set later with `setSlackUsersCap`.
You can see also in our tests that we call `setSlackUsersCap` explicitly.
7 is just a nice number. It has no meaning. I could just as well init it to 0.

**Comment by IsaacPayne** [comment]
I think initialising to `0` with a comment would be our best bet here

**Comment by yaronvel** [comment]
Added a comment, but left it as `7`.
Setting default to `0` will not make it possible to distinguish between addresses that didn't register.
And `7` is a nice number.

**Comment by OperationNine** [comment]
- [x] Fixed [9b6769ac](https://github.com/KyberNetwork/TokenDistributionContracts/commit/9b6769ac4087c36f28470b4f9507cc3dea4c8995)
