### ISSUE TITLE
Use `getTime()` rather than now

### ISSUE THREAD

**Issue by IsaacPayne** [BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts#19]
Using  and overriding `getTime()` for tests saves us having to deal with `evm_increaseTime`

`KyberNetworkTokenSale`
```
    /// @notice This function is overriden by the test Mocks.
    function getTime() internal returns (uint256) {
        return now;
    }
```

`KyberNetworkTokenSaleMock`
```
    uint256 mock_time;

    function KyberNetworkTokenSaleMock(...)
            KyberNetworkTokenSale(...) {
        mock_time = now;
    }

    function getTime() internal returns (uint256) {
        return mock_time;
    }

    function setMockedTime(uint256 _t) public {
        mock_time = _t;
    }
```

**Comment by yaronvel** [comment]
Nice trick. But there are also obvious down sides to it.
I guess the best thing would be to use both `evm_increaseTime` in testrpc on the actual code (and not on the mock) and `setTime` on testnet/mainnet test with mock code.
