### ISSUE TITLE
Check dates are valid

### ISSUE THREAD

**Issue by IsaacPayne** [BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts#3]
To protect against user error, we would recommend adding a `require` in to check the `startTime` is less than `endTime`, as this would mess with `onlyWhenTransferEnabled()`

https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/KyberNetworkCrystal.sol#L35-L36

**Comment by yaronvel** [comment]
This is done here
https://github.com/KyberNetwork/TokenDistributionContracts/blob/master/TokenSale/contracts/ContributorApprover.sol#L28

Though it might make sense doing it also in the token contract.

**Comment by IsaacPayne** [comment]
Cool closing this as it's checked here:
https://github.com/KyberNetwork/TokenDistributionContracts/blob/master/TokenSale/contracts/ContributorApprover.sol#L28
