### ISSUE TITLE
Fix grammatical errors

### ISSUE THREAD

**Issue by OperationNine** [BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts#6]
Fix grammatical errors and spelling mistakes

optamisation => optimization

`KyberContributorWhitelist`
https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/KyberContirbutorWhitelist.sol#L20

contirbutor => contributor

`Approver.sol`
https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/mock/Approver.sol#L7

`ContributorApprover.sol`
https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/ContributorApprover.sol#L4
https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/ContributorApprover.sol#L8
https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/ContributorApprover.sol#L18
https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/ContributorApprover.sol#L27

`KyberContributorWhitelist.sol` -- Name also needs correct spelling 
https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/KyberContirbutorWhitelist.sol#L5
https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/KyberContirbutorWhitelist.sol#L9

`KyberNetworkTokenSale.sol`
https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/KyberNetworkTokenSale.sol#L5
https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/KyberNetworkTokenSale.sol#L18

fix spacing

`KyberNetworkTokenSale.sol`
https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/KyberNetworkTokenSale.sol#L96
https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/KyberNetworkTokenSale.sol#L107

**Comment by yaronvel** [comment]
Thanks. Will do.

**Comment by OperationNine** [comment]
- [x] Fixed [3023673d](https://github.com/KyberNetwork/TokenDistributionContracts/commit/3023673dc54a6bf4426ed0814f9652d5586f6c07), [6b04dbf7](https://github.com/KyberNetwork/TokenDistributionContracts/commit/6b04dbf730ffc55c3d2850969dbbfb89e69dfcfc)
