### ISSUE TITLE
Add relevant variables to deploy_contracts migration

### ISSUE THREAD

**Issue by OperationNine** [BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts#8]
If deploying from truffle via `truffle migrate` then these variables will need to be updated with the contract names of those being deployed.

https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/migrations/2_deploy_contracts.js#L1-L2

**Comment by yaronvel** [comment]
We will do it once we know the final values of these parameters.
