### ISSUE TITLE
Event variable naming consistancy

### ISSUE THREAD

**Issue by IsaacPayne** [BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts#9]
`ProxyBuy` and `Buy` don't follow the underscore(`_`) convention used by the rest of the code

https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/KyberNetworkTokenSale.sol#L51

https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/KyberNetworkTokenSale.sol#L58

**Comment by yaronvel** [comment]
Thanks. will do.

**Comment by OperationNine** [comment]
- [x] Fixed [e2ab7441](https://github.com/KyberNetwork/TokenDistributionContracts/commit/e2ab7441a5f7b7046a5a975464465c1136ca447f)
